### ISSUE TITLE
chat history 

### ISSUE THREAD

**Issue by ahmedRSA** [otiai10/openaigo#19]
### Describe the bug

project that saves chat history to db
and then use history in context

### To Reproduce

.

### OS

Windows

### Go version

1.18

### Library version

Latest

**Comment by otiai10** [comment]
is it a bug?

**Comment by ahmedRSA** [comment]
sorry but it does not let me create an issue without bug label

**Comment by otiai10** [comment]
Use `[]ChatMessage` as history. Please refer to this https://platform.openai.com/docs/guides/chat/introduction

**Comment by otiai10** [comment]
This is my example app to preserve conversation history
https://github.com/otiai10/hi

**Comment by ahmedRSA** [comment]
i think chat history feature should be added into package itself because without history (context) chatgpt api is useless.

Anyway thanks for reply.

**Comment by otiai10** [comment]
Official API says that we, developers, should preserve conversation to keep context, thus we can just use `[]openaigo.ChatMessage` as like `conversation`.
This is users' responsibility to control (for example, preventing max token error from API is really what user-side should handle) and preserve the conversation, and I don't think this package should do that.
